[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mongodb]
command=mongod --dbpath /data/db --bind_ip 127.0.0.1 --logpath /var/log/mongodb/mongod.log
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/mongodb.log
stderr_logfile=/var/log/supervisor/mongodb_err.log

[program:backend]
command=node server.js
autostart=true
autorestart=true
priority=20
startsecs=5
directory=/app/backend
stdout_logfile=/var/log/supervisor/backend.log
stderr_logfile=/var/log/supervisor/backend_err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log